### ISSUE TITLE
AirVisual JSON format issue

### ISSUE THREAD

**Issue by adintegra** [deanlyoung/homebridge-airvisual-pro#2]
I've found that my AirVisual (System Version: KBG60F82 / Software Version: 1.1651) writes its measurements into a JSON object _within an array_ rather than just into a straight JSON object, i.e.:

**that.airdata.measurements[0].pm25_AQIUS** as opposed to just **that.airdata.measurements.pm25_AQIUS**

In my case then, the plugin was initially not finding any measurements. A quick search-and-replace did the trick. It's possible that others are experiencing the same problem so it may be worth implementing a more generic fix catering to both formats.

Great plugin – thanks!

**Comment by ev3rest** [comment]
You should create a pull request. This actually fixed my error. Thank you!

**Comment by Vovoronale** [comment]
Can someone explain where I need made changes?

**Comment by adintegra** [comment]
Created pull request: #3

**Comment by leonroy** [comment]
@deanlyoung the current `homebridge-airvisual-pro` plugin no longer resolves any values:
![image](https://user-images.githubusercontent.com/325602/80317353-4147ff80-87fb-11ea-9986-2637d6c7c178.png)

PR #3 looks like it should resolve the issue. Don't suppose you can merge it? Save some head ache trying to figure out how to use @adintegra's github fork in my Homebridge Docker `package.json` file.

Thanks!
